# osCommerce Website
#
# @copyright Copyright (c) 2012 osCommerce; http://www.oscommerce.com
# @license BSD License; http://www.oscommerce.com/bsdlicense.txt

personal_html_page_title = osCommerce, It's personal, not business.

personal_page_title = Personal Matters

personal_main_content = <dl><dt style="padding-bottom: 10px;">Self-Made and Self-Funded</dt><dd><p>osCommerce was first announced to the world in March 2000 with a simple and general online store solution to see if others were interested in building onto it. It was released as Open Source to not only allow others to view the source code but to also edit it and have changes contributed back to the core solution everyone else could use and benefit from. What followed was the start of strangers collaborating all over the world who were each helping each other out, forming great friendships that still exist today, and building a team that is dedicated to managing the demands of a growing community.</p><p>We have been running successfully for {value}sweet_sixteen{value} years without financial investments and are proud to be able to focus 100% on the community.</dd><dt style="padding-bottom: 10px;">Community Engagement</dt><dd><p>We are there in the middle of the community helping store owners out and helping developers helping us out with the core of our products. We communicate each change we make with the community and directly reply to the feedback provided. You can contact each team member directly and can even find us at times in the Live Chat room.</p><p>We're personally there for you because we love the work we do and cherish the support given back in general.</p></dd><dt style="padding-bottom: 10px;">Passion</dt><dd><p>This is our passion. We are not seeking a quick exit nor multi-million dollar investments. Our success was never built on hype. We are proud with what we have personally achieved ourselves and even prouder of the achievements made with the community. We are proud of having helped store owners around the world and even prouder of the thanks received in return.</p><p>And we are at most proud of the community who share the same passion and graciously help others moving forward.</p><p>Thank you.</p></dd></dl>
